<?php
/**
 * IMPORTADOR DE CATÁLOGO - Manizales Perfumería
 * =============================================
 * 
 * IMPORTA 90 PERFUMES DE MUJER A LA BASE DE DATOS.
 * 
 * INSTRUCCIONES:
 * 1. Sube este archivo a la raíz de tu sitio en InfinityFree
 * 2. Visita: https://manizales-pf.great-site.net/importar_catalogo.php
 * 3. Espera a que termine (puede tomar 30-60 segundos)
 * 4. ELIMINA este archivo después de usarlo por seguridad
 * 
 * Este script crea la tabla si no existe e inserta los 90 productos.
 */

// No hay tiempo límite para la importación
set_time_limit(120);

// Configuración de base de datos
$db_host = 'sql210.infinityfree.com';
$db_name = 'if0_42231882_manizales';
$db_user = 'if0_42231882';
$db_pass = '1q2w3e45T5T678i';

echo "<!DOCTYPE html>
<html lang='es'>
<head>
    <meta charset='UTF-8'>
    <title>Importando Catálogo - Manizales Perfumería</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; background: #f5f5f5; padding: 40px; color: #333; }
        .container { max-width: 700px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #C9A96E; margin-bottom: 10px; }
        .subtitle { color: #666; margin-bottom: 30px; }
        .status { padding: 12px 16px; margin: 8px 0; border-radius: 4px; font-size: 14px; }
        .status--ok { background: #ECFDF5; color: #065F46; border-left: 4px solid #10B981; }
        .status--error { background: #FEF2F2; color: #991B1B; border-left: 4px solid #EF4444; }
        .status--info { background: #EFF6FF; color: #1E40AF; border-left: 4px solid #3B82F6; }
        .status--warning { background: #FFFBEB; color: #92400E; border-left: 4px solid #F59E0B; }
        .progress { width: 100%; height: 8px; background: #E5E7EB; border-radius: 4px; margin: 16px 0; overflow: hidden; }
        .progress__bar { height: 100%; background: #C9A96E; border-radius: 4px; transition: width 0.3s ease; }
        .count { font-size: 48px; font-weight: 700; color: #C9A96E; text-align: center; margin: 20px 0; }
        .count-label { text-align: center; color: #666; margin-bottom: 20px; }
        .btn { display: inline-block; padding: 12px 24px; background: #C9A96E; color: white; text-decoration: none; border-radius: 4px; font-weight: 600; margin-top: 20px; }
        .btn:hover { background: #B8860B; }
        .footer-note { margin-top: 30px; padding-top: 20px; border-top: 1px solid #E5E7EB; color: #999; font-size: 12px; }
    </style>
</head>
<body>
<div class='container'>
    <h1>Manizales Perfumería</h1>
    <p class='subtitle'>Importación automática de catálogo - 90 perfumes de mujer</p>
    <div class='progress'><div class='progress__bar' id='progress' style='width: 0%'></div></div>
    <div id='output'></div>
</div>
</body>
</html>";

function addStatus($msg, $type = 'info') {
    echo "<div class='status status--$type'>$msg</div>";
    @ob_flush();
    @flush();
}

function updateProgress($pct) {
    echo "<script>document.getElementById('progress').style.width='" . $pct . "%';</script>";
    @ob_flush();
    @flush();
}

// Conectar a la base de datos
try {
    $pdo = new PDO(
        "mysql:host=$db_host;dbname=$db_name;charset=utf8mb4",
        $db_user,
        $db_pass,
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false
        ]
    );
    addStatus("Conectado a la base de datos correctamente.", "ok");
    updateProgress(5);
} catch (PDOException $e) {
    addStatus("Error de conexión: " . $e->getMessage(), "error");
    die();
}

// Verificar si la tabla productos existe
try {
    $result = $pdo->query("SHOW TABLES LIKE 'productos'");
    if ($result->rowCount() == 0) {
        addStatus("La tabla 'productos' no existe. Creándola...", "warning");
        $pdo->exec("CREATE TABLE IF NOT EXISTS `productos` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `nombre` VARCHAR(255) NOT NULL,
            `marca` VARCHAR(100) NOT NULL,
            `descripcion` TEXT,
            `descripcion_corta` TEXT,
            `precio` DECIMAL(10,2) DEFAULT NULL,
            `precio_anterior` DECIMAL(10,2) DEFAULT NULL,
            `imagen` VARCHAR(255) DEFAULT NULL,
            `categoria` ENUM('hombre', 'mujer') NOT NULL,
            `tipo_olor` VARCHAR(100) NOT NULL,
            `notas` TEXT,
            `notas_salida` VARCHAR(255) DEFAULT NULL,
            `notas_corazon` VARCHAR(255) DEFAULT NULL,
            `notas_fondo` VARCHAR(255) DEFAULT NULL,
            `tamanio` VARCHAR(50) DEFAULT NULL,
            `emoji` VARCHAR(10) DEFAULT '✦',
            `en_promocion` TINYINT(1) DEFAULT 0,
            `destacado` TINYINT(1) DEFAULT 0,
            `activo` TINYINT(1) DEFAULT 1,
            `transmite` TEXT,
            `ideal_para` TEXT,
            `duracion` VARCHAR(100) DEFAULT NULL,
            `intensidad` VARCHAR(100) DEFAULT NULL,
            `colores` TEXT,
            `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        addStatus("Tabla 'productos' creada exitosamente.", "ok");
    } else {
        // Verificar y agregar columnas que falten
        $columns = $pdo->query("SHOW COLUMNS FROM productos")->fetchAll(PDO::FETCH_COLUMN);
        $neededCols = [
            'descripcion_corta' => "ALTER TABLE productos ADD COLUMN `descripcion_corta` TEXT AFTER `descripcion`",
            'transmite' => "ALTER TABLE productos ADD COLUMN `transmite` TEXT AFTER `intensidad`",
            'ideal_para' => "ALTER TABLE productos ADD COLUMN `ideal_para` TEXT AFTER `transmite`",
            'duracion' => "ALTER TABLE productos ADD COLUMN `duracion` VARCHAR(100) DEFAULT NULL AFTER `ideal_para`",
            'intensidad' => "ALTER TABLE productos ADD COLUMN `intensidad` VARCHAR(100) DEFAULT NULL AFTER `duracion`",
            'colores' => "ALTER TABLE productos ADD COLUMN `colores` TEXT AFTER `intensidad`"
        ];
        foreach ($neededCols as $col => $sql) {
            if (!in_array($col, $columns)) {
                $pdo->exec($sql);
                addStatus("Columna '$col' agregada.", "ok");
            }
        }
        addStatus("Tabla 'productos' verificada. Columnas actualizadas.", "ok");
    }
    updateProgress(10);
} catch (PDOException $e) {
    addStatus("Error verificando tabla: " . $e->getMessage(), "error");
    die();
}

// Verificar cuántos productos hay actualmente
$countResult = $pdo->query("SELECT COUNT(*) as total FROM productos WHERE categoria = 'mujer'");
$currentCount = $countResult->fetch()['total'];
addStatus("Productos de mujer actuales en la base: $currentCount", "info");

if ($currentCount >= 90) {
    addStatus("Ya hay 90+ productos de mujer. Saltando importación.", "warning");
    addStatus("Si quieres re-importar, elimina los productos existentes primero.", "warning");
} else {
    // Productos a insertar
    $productos = [
        // Each product: [nombre, marca, descripcion, desc_corta, imagen, tipo_olor, notas, notas_salida, notas_corazon, notas_fondo, emoji, transmite, ideal_para, duracion, intensidad, colores]
        ['9 Am Pour Femme', 'Afnan', 'Una fragancia vibrante y moderna que captura la energía de una mujer segura de sí misma. Su apertura cítrica con bergamota y pomelo despierta los sentidos, mientras que el corazón floral de jazmín y peonía envuelve en ternura.', 'Fragancia vibrante y moderna con notas cítricas y florales.', 'img/productos/afnan-9am-pour-femme.jpg', 'floral', 'Bergamota, pomelo, jazmín, peonía, almizcle blanco, sándalo', 'Bergamota, pomelo, lichi', 'Jazmín, peonía, magnolia', 'Almizcle blanco, sándalo, ámbar', '🌸', 'Frescura, feminidad, energía, ternura', 'Días soleados, uso diario, citas informales, primavera', '6-8 horas', 'Moderada', '{"principal":"#F472B6","secundario":"#FBCFE8","acento":"#DB2777","fondo":"#FFF1F7"}'],
        ['Club de Nuit', 'Armaf', 'Una interpretación audaz y seductora de las fragancias de diseñador. Su apertura especiada con pimienta rosa y cardamomo crea una entrada magnética, seguida de un corazón de rosa turca y oud que enamora.', 'Seductora y especiada, perfecta para noches inolvidables.', 'img/productos/armaf-club-de-nuit.jpg', 'oriental', 'Pimienta rosa, cardamomo, rosa turca, oud, vainilla, almizcle', 'Pimienta rosa, cardamomo, bergamota', 'Rosa turca, oud, jazmín', 'Vainilla, almizcle blanco, ámbar gris', '🌙', 'Seducción, misterio, poder, elegancia nocturna', 'Noches de fiesta, citas románticas, eventos especiales', '8-10 horas', 'Alta', '{"principal":"#7C3AED","secundario":"#DDD6FE","acento":"#5B21B6","fondo":"#F5F3FF"}'],
        ['Isabella', 'Armaf', 'Un ramo de flores frescas recién cortadas del jardín. Isabella combina la dulzura de la fresa con la elegancia del lirio del valle y la calidez del almizcle.', 'Un ramo de flores frescas con dulzura de fresa y elegancia del jardín.', 'img/productos/armaf-isabella.jpg', 'floral', 'Fresa, lirio del valle, peonía, almizcle, musgo de roble', 'Fresa, pera, bergamota', 'Lirio del valle, peonía, jazmín', 'Almizcle, musgo de roble, vainilla suave', '🌷', 'Inocencia, dulzura, frescura primaveral, ternura', 'Uso diario, oficina, paseos, primavera y verano', '5-7 horas', 'Moderada', '{"principal":"#F9A8D4","secundario":"#FDE68A","acento":"#EC4899","fondo":"#FFF7ED"}'],
        ['Cloud', 'Ariana Grande', 'Una nube de felicidad en forma de fragancia. Cloud es pura energía positiva: la frescura del coco se mezcla con la dulzura de la lavanda y la crema de vainilla para crear un aroma adictivo y reconfortante.', 'Una nube de felicidad: coco, lavanda y vainilla que crean un aroma adictivo.', 'img/productos/ariana-grande-cloud.jpg', 'dulce', 'Coco, lavanda, vainilla, almizcle, pera', 'Lavanda, pera, bergamota', 'Coco, jasmine, praline', 'Vainilla, almizcle blanco, madera de cachemira', '☁️', 'Felicidad, despreocupación, dulzura, energía positiva', 'Citas informales, verano, uso diario, fins de semana', '6-8 horas', 'Moderada', '{"principal":"#818CF8","secundario":"#C7D2FE","acento":"#6366F1","fondo":"#EEF2FF"}'],
        ['Cloud Pink', 'Ariana Grande', 'La hermana rosada de Cloud, más femenina y romántica. Fusiona la frescura de la fresa con la ternura de la peonía y la calidez del sándalo.', 'La versión rosada y romántica de Cloud: fresa, peonía y sándalo.', 'img/productos/ariana-grande-cloud-pink.jpg', 'floral', 'Fresa, peonía, sándalo, vainilla, almizcle', 'Fresa, toronja, lichi', 'Peonía, jazmín, rosa', 'Sándalo, vainilla, almizcle blanco', '🩷', 'Romanticismo, dulzura, feminidad, ternura', 'Citas románticas, verano, uso diario, primavera', '5-7 horas', 'Moderada', '{"principal":"#FB7185","secundario":"#FECDD3","acento":"#E11D48","fondo":"#FFF1F2"}'],
        ['Sweet Like Candy', 'Ariana Grande', 'Pura dulzura en estado puro. Sweet Like Candy es un caramelo líquido: fresa, mora y crema de vainilla se unen para crear un aroma que es pura tentación.', 'Pura dulzura: fresa, mora y crema de vainilla en estado líquido.', 'img/productos/ariana-grande-sweet-like-candy.jpg', 'dulce', 'Fresa, mora, vainilla, crema, almizcle', 'Fresa, mora, grosella', 'Crema de vainilla, praline, flor de azahar', 'Almizcle blanco, sándalo, vainilla', '🍬', 'Dulzura, juguetearía, tentación, alegría', 'Citas informales, verano, uso diario, fins de semana', '5-7 horas', 'Moderada', '{"principal":"#F43F5E","secundario":"#FECDD3","acento":"#BE123C","fondo":"#FFF1F2"}'],
        ['Extatic', 'Balmain', 'La esencia de la haute couture en una botella. Extatic es lujo puro: notas de iris y alhelgi se combinan con un fondo de ámbar y almizcle para crear una fragancia que grita elegancia.', 'Lujo de haute couture: iris, alhelgi y ámbar en elegancia pura.', 'img/productos/balmain-extatic.jpg', 'elegante', 'Iris, alhelgi, ámbar, almizcle, madera de cachemira', 'Bergamota, pera, alhelgi', 'Iris, rosa, jazmín', 'Ámbar, almizcle, sándalo, vainilla', '✨', 'Elegancia, poder, sofisticación, lujo', 'Eventos formales, cenas de gala, noches especiales', '8-12 horas', 'Alta', '{"principal":"#D4AF37","secundario":"#FDE68A","acento":"#B8860B","fondo":"#FFFBEB"}'],
        ['Her', 'Burberry', 'El espíritu de Londres en una fragancia. Her es vibrante, libre y adictiva: la explosión de frutos rojos se mezcla con la elegancia de la peonía y el fondo de almizcle y ámbar.', 'El espíritu londinense: frutos rojos vibrantes, peonía y almizcle adictivo.', 'img/productos/burberry-her.jpg', 'floral', 'Frutos rojos, peonía, almizcle, ámbar, violeta', 'Fresa, frambuesa, limón', 'Peonía, jazmín, violeta', 'Almizcle, ámbar, sándalo, vainilla', '🇬🇧', 'Libertad, pasión, modernidad, energía', 'Uso diario, oficina, citas, todo el año', '7-9 horas', 'Moderada', '{"principal":"#DC2626","secundario":"#FCA5A5","acento":"#B91C1C","fondo":"#FEF2F2"}'],
        ['Her Intense', 'Burberry', 'La versión más profunda y seductora de Her. Los frutos rojos se intensifican con la adición de rosa negra y patchouli, creando una fragancia más oscura y misteriosa.', 'La versión intensa y oscura: frutos rojos, rosa negra y patchouli seductor.', 'img/productos/burberry-her-intense.jpg', 'oriental', 'Frutos rojos, rosa negra, patchouli, ámbar, vainilla', 'Frambuesa, grosella negra, pimienta', 'Rosa negra, peonía, jazmín', 'Patchouli, ámbar, vainilla, almizcle', '🔥', 'Misterio, pasión oscura, seducción, poder', 'Noches de fiesta, citas románticas, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#991B1B","secundario":"#DC2626","acento":"#7F1D1D","fondo":"#FEF2F2"}'],
        ['Amor Amor', 'Cacharel', 'Una carta de amor en forma de fragancia. Amor Amor es pasión pura: la fresa y la mora se mezclan con la rosa y el jazmín en un abrazo aromático que calienta el corazón.', 'Una carta de amor: fresa, mora, rosa y jazmín en un abrazo aromático.', 'img/productos/cacharel-amor-amor.jpg', 'floral', 'Fresa, mora, rosa, jazmín, vainilla, almizcle', 'Fresa, mandarina, lichi', 'Rosa, jazmín, lirio', 'Vainilla, almizcle, cedro', '❤️', 'Pasión, romance, aventura, ternura', 'Citas románticas, noches de amor, primavera', '6-8 horas', 'Moderada', '{"principal":"#E11D48","secundario":"#FECDD3","acento":"#BE123C","fondo":"#FFF1F2"}'],
        ['212 NYC', 'Carolina Herrera', 'La energía de Manhattan en una fragancia. 212 NYC captura la esencia de la mujer que vive la ciudad que nunca duerme: fresca, vibrante y siempre en movimiento.', 'La energía de Manhattan: naranja amarga, gardenia y almizcle urbano.', 'img/productos/carolina-herrera-212-nyc.jpg', 'fresco', 'Naranja amarga, gardenia, almizcle, sándalo, bergamota', 'Naranja amarga, bergamota, lila', 'Gardenia, jazmín, rosa', 'Almizcle, sándalo, ámbar', '🏙️', 'Energía urbana, modernidad, frescura, estilo', 'Uso diario, oficina, verano, todo el año', '6-8 horas', 'Moderada', '{"principal":"#0EA5E9","secundario":"#BAE6FD","acento":"#0284C7","fondo":"#F0F9FF"}'],
        ['212 VIP', 'Carolina Herrera', 'La lista VIP de las fragancias. 212 VIP es pura exclusividad: el aroma de la pasión de maracuyá y el jengibre se mezcla con la elegancia de la gardenia y el tonka.', 'Exclusividad pura: pasión de maracuyá, jengibre y elegancia de gardenia.', 'img/productos/carolina-herrera-212-vip.jpg', 'oriental', 'Maracuyá, jengibre, gardenia, tonka, almizcle', 'Maracuyá, limón, jengibre', 'Gardenia, jazmín, rosas', 'Tonka, almizcle, sándalo, vainilla', '💎', 'Exclusividad, seducción, poder, magnetismo', 'Noches de fiesta, eventos VIP, citas especiales', '8-10 horas', 'Alta', '{"principal":"#F59E0B","secundario":"#FDE68A","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['Good Girl', 'Carolina Herrera', 'La dualidad de la mujer moderna. Good Girl es dulce pero peligrosa: la dulzura del chocolate y la avellana se mezcla con la intensidad del café y el jengibre.', 'Dualidad pura: dulzura de chocolate y avellana con intensidad de café.', 'img/productos/carolina-herrera-good-girl.jpg', 'dulce', 'Chocolate, avellana, café, jengibre, jazmín, tonka', 'Almendra, café, pimienta', 'Jazmín, tuberosa, rosa', 'Tonka, cacao, vainilla, sándalo', '👠', 'Dualidad, elegancia, misterio, seducción peligrosa', 'Noches de fiesta, citas románticas, otoño/invierno', '8-12 horas', 'Alta', '{"principal":"#1F2937","secundario":"#6B7280","acento":"#374151","fondo":"#F9FAFB"}'],
        ['Chance Eau Fraîche', 'Chanel', 'La suerte de encontrar la frescura perfecta. Chance Eau Fraîche es como una brisa primaveral: el citronelos y el jazmín se abren con ligereza.', 'Brisa primaveral: citronelos, jazmín y vetiver en elegancia ligera.', 'img/productos/chanel-chance-eau-fraiche.jpg', 'fresco', 'Citronelos, jazmín, vetiver, cedro, almizcle', 'Citronelos, lichi, bergamota', 'Jazmín, lirio del valle', 'Vetiver, cedro, almizcle blanco', '🍀', 'Frescura, optimismo, juventud, suerte', 'Primavera, verano, uso diario, oficina', '6-8 horas', 'Moderada', '{"principal":"#86EFAC","secundario":"#BBF7D0","acento":"#22C55E","fondo":"#F0FDF4"}'],
        ['Chance Eau Tendre', 'Chanel', 'La ternura hecha fragancia. Chance Eau Tendre es suave como un cariño: la manzana y la gardenia se mezclan con el almizcle y el sándalo.', 'Ternura perfecta: manzana, gardenia y almizcle en suavidad balanceada.', 'img/productos/chanel-chance-eau-tendre.jpg', 'floral', 'Manzana, gardenia, almizcle, sándalo, iris', 'Manzana, pomelo, lichi', 'Gardenia, jazmín, iris', 'Almizcle, sándalo, vainilla suave', '💕', 'Ternura, suavidad, elegancia, dulzura balanceada', 'Citas románticas, uso diario, primavera, todo el año', '6-8 horas', 'Moderada', '{"principal":"#F9A8D4","secundario":"#FDE68A","acento":"#EC4899","fondo":"#FFF7ED"}'],
        ['Coco Mademoiselle', 'Chanel', 'La icónica fragancia de la mujer independiente. Coco Mademoiselle es elegancia pura: las notas de naranja y bergamota abren con frescura, mientras que la rosa y el jazmín crean un corazón floral sofisticado.', 'Icónica elegancia: naranja, rosa, patchouli y vainilla en perfección.', 'img/productos/chanel-coco-mademoiselle.jpg', 'elegante', 'Naranja, bergamota, rosa, jazmín, patchouli, vainilla', 'Naranja, bergamota, pomelo', 'Rosa, jazmín, lirio', 'Patchouli, vainilla, almizcle, ámbar', '👑', 'Independencia, elegancia, sofisticación, poder', 'Cualquier ocasión, todo el año, día y noche', '8-12 horas', 'Alta', '{"principal":"#D4AF37","secundario":"#FDE68A","acento":"#B8860B","fondo":"#FFFBEB"}'],
        ['No. 5', 'Chanel', 'La fragancia más famosa del mundo. Chanel No. 5 es atemporal: el aldehído crea una apertura única, seguida de un corazón de rosa y jazmín que ha sido amado por generaciones.', 'La leyenda atemporal: aldehído, rosa, jazmín y sándalo en perfección eterna.', 'img/productos/chanel-no5.jpg', 'elegante', 'Aldehído, rosa, jazmín, sándalo, almizcle, vetiver', 'Aldehído, bergamota, limón', 'Rosa, jazmín, lirio', 'Sándalo, almizcle, vetiver, ámbar', '5', 'Atemporalidad, elegancia, lujo, legado', 'Eventos formales, cenas elegantes, toda ocasión especial', '10-14 horas', 'Alta', '{"principal":"#FDE68A","secundario":"#FEF3C7","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['Love Story', 'Chloe', 'Una historia de amor parisina en forma de fragancia. Love Story es romántica y luminosa: la naranja y el mirto abren con frescura, mientras que la flor de azahar y la rosa crean un corazón delicado.', 'Historia de amor parisina: naranja, flor de azahar y almizcle luminoso.', 'img/productos/chloe-love-story.jpg', 'floral', 'Naranja, mirto, flor de azahar, rosa, almizcle, cedro', 'Naranja, pera, bergamota', 'Flor de azahar, rosa, jazmín', 'Almizcle, cedro, hojas de olivo', '💕', 'Romanticismo, luminosidad, ternura, esperanza', 'Citas románticas, primavera, uso diario, bodas', '6-8 horas', 'Moderada', '{"principal":"#FCA5A5","secundario":"#FEE2E2","acento":"#EF4444","fondo":"#FEF2F2"}'],
        ['Flower', 'Coach', 'El espíritu americano en una fragancia floral. Flower es vibrante y libre: la rosa y el jazmín se mezclan con notas frutales para crear un aroma que es pura energía.', 'Espíritu americano: rosa, jazmín y frutas en vibración libre.', 'img/productos/coach-flower.jpg', 'floral', 'Rosa, jazmín, frutas rojas, almizcle, cedro', 'Frambuesa, pomelo, pera', 'Rosa, jazmín, peonía', 'Almizcle, cedro, sándalo', '🌺', 'Libertad, energía, aventura, optimismo', 'Primavera, verano, uso diario, paseos', '6-8 horas', 'Moderada', '{"principal":"#F472B6","secundario":"#FBCFE8","acento":"#DB2777","fondo":"#FFF1F7"}'],
        ['Addict', 'Dior', 'Adictiva por naturaleza. Addict es una fragancia que no puedes dejar: la dulzura de la flor de azahar se mezcla con la intensidad del café y la vainilla.', 'Adictiva: flor de azahar, café y vainilla en intensidad magnética.', 'img/productos/dior-addict.jpg', 'oriental', 'Flor de azahar, café, vainilla, almizcle, sándalo', 'Flor de azahar, naranja', 'Café, jazmín, rosa', 'Vainilla, almizcle, sándalo', '🌀', 'Adicción, intensidad, magnetismo, deseo', 'Noches de fiesta, citas románticas, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#7C3AED","secundario":"#DDD6FE","acento":"#5B21B6","fondo":"#F5F3FF"}'],
        ['Hypnotic Poison', 'Dior', 'El veneno más seductor del mundo. Hypnotic Poison es oscura y adictiva: el coco se mezcla con almendras amargas, mientras que el jazmín y el almizcle crean una trampa aromática.', 'Veneno seductor: coco, almendras amargas y jazmín en trampa aromática.', 'img/productos/dior-hypnotic-poison.jpg', 'oriental', 'Coco, almendras, jazmín, almizcle, sándalo, vainilla', 'Coco, almendras amargas', 'Jazmín, tuberosa, rosa', 'Almizcle, sándalo, vainilla, ámbar', '🐍', 'Seducción oscura, misterio, peligro, magnetismo', 'Noches de fiesta, citas intensas, otoño/invierno', '10-12 horas', 'Muy Alta', '{"principal":"#B91C1C","secundario":"#FCA5A5","acento":"#991B1B","fondo":"#FEF2F2"}'],
        ['J\'adore', 'Dior', 'Una ode a la feminidad. J\'adore es pura luz: la magnolia, la rosa y el jazmín se entrelazan en un bouquet floral que irradia alegría y elegancia.', 'Ode a la feminidad: magnolia, rosa y jazmín en bouquet luminoso.', 'img/productos/dior-jadore.jpg', 'floral', 'Magnolia, rosa, jazmín, peonía, almizcle', 'Bergamota, pera, magnolia', 'Rosa, jazmín, peonía', 'Almizcle, sándalo, vainilla', '💛', 'Feminidad, alegría, elegancia, luz', 'Todo el año, día y noche, cualquier ocasión', '8-10 horas', 'Moderada-Alta', '{"principal":"#F59E0B","secundario":"#FDE68A","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['J\'adore Diorissimo', 'Dior', 'La versión más pura y delicada de J\'adore. Diorissimo es como un ramo de flores silvestres: el lirio del valle y el jazmín crean una sinfonía suave y etérea.', 'La pureza de J\'adore: lirio del valle y jazmín en delicadeza etérea.', 'img/productos/dior-jadore-diorissimo.jpg', 'floral', 'Lirio del valle, jazmín, peonía, almizcle, musgo', 'Lirio del valle, bergamota', 'Jazmín, peonía, rosa', 'Almizcle, musgo de roble', '🤍', 'Pureza, naturalidad, delicadeza, transparencia', 'Primavera, verano, uso diario, oficina', '5-7 horas', 'Suave', '{"principal":"#F0FDF4","secundario":"#DCFCE7","acento":"#22C55E","fondo":"#F0FDF4"}'],
        ['Miss Dior', 'Dior', 'La elegancia de la nouvelle vague francesa. Miss Dior es sofisticada y romántica: la peonía y el lirio del valle se mezclan con notas de rosa y almizcle.', 'Elegancia de la Nouvelle Vague: peonía, lirio del valle y rosa sofisticada.', 'img/productos/dior-miss-dior.jpg', 'floral', 'Peonía, lirio del valle, rosa, almizcle, patchouli', 'Bergamota, naranja', 'Peonía, lirio del valle, jazmín', 'Rosa, almizcle, patchouli', '🎀', 'Elegancia, romanticismo, gracia, rebeldía juvenil', 'Citas románticas, eventos formales, todo el año', '8-10 horas', 'Moderada-Alta', '{"principal":"#F9A8D4","secundario":"#FBCFE8","acento":"#EC4899","fondo":"#FFF1F7"}'],
        ['Light Blue', 'Dolce & Gabbana', 'El Mediterráneo en una fragancia. Light Blue es pura luz de verano: la manzana siciliana y el cedro se abren con frescura, mientras que el jazmín y el bambú crean un corazón luminoso.', 'Mediterráneo puro: manzana siciliana, cedro y jazmín en luz de verano.', 'img/productos/dolce-gabbana-light-blue.jpg', 'fresco', 'Manzana, cedro, jazmín, bambú, almizcle', 'Manzana siciliana, bergamota, campanilla', 'Jazmín, bambú, rosa blanca', 'Cedro, almizcle, ámbar', '🌊', 'Frescura, luz, alegría veraniega, naturalidad', 'Verano, playas, uso diario, paseos', '5-7 horas', 'Suave-Moderada', '{"principal":"#38BDF8","secundario":"#BAE6FD","acento":"#0284C7","fondo":"#F0F9FF"}'],
        ['Pour Femme', 'Dolce & Gabbana', 'La femineidad italiana en su máxima expresión. Pour Femme es cálida y envolvente: la naranja y la lila se abren con dulzura, mientras que la gardenia y el jazmín crean un corazón sensual.', 'Femineidad italiana: naranja, gardenia y vainilla en abrazo cálido.', 'img/productos/dolce-gabbana-pour-femme.jpg', 'floral', 'Naranja, lila, gardenia, jazmín, vainilla, almizcle', 'Naranja, bergamota, lila', 'Gardenia, jazmín, naranja en flor', 'Vainilla, almizcle, sándalo', '🇮🇹', 'Calidez, pasión italiana, sensualidad, elegancia', 'Citas románticas, otoño/invierno, noches especiales', '7-9 horas', 'Moderada', '{"principal":"#F59E0B","secundario":"#FDE68A","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['The One', 'Dolce & Gabbana', 'La única. The One es pura sofisticación: la durazno y la lichi se mezclan con el jazmín y la rosa para crear una fragancia que es elegancia concentrada.', 'La única: durazno, lichi y jazmín en sofisticación concentrada.', 'img/productos/dolce-gabbana-the-one.jpg', 'oriental', 'Durazno, lichi, jazmín, rosa, vainilla, almizcle', 'Durazno, lichi, bergamota', 'Jazmín, rosa, lirio', 'Vainilla, almizcle, ámbar', '🌟', 'Sofisticación, exclusividad, elegancia, serenidad', 'Cenas elegantes, eventos formales, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#D4AF37","secundario":"#FDE68A","acento":"#B8860B","fondo":"#FFFBEB"}'],
        ['5th Avenue', 'Elizabeth Arden', 'La avenida más famosa del mundo en una fragancia. 5th Avenue es elegancia urbana: la lilas y el magnolia crean una sinfonía floral que evoca los rascacielos y las boutique de lujo.', 'Elegancia urbana: lilas y magnolia en sinfonía de la avenida más famosa.', 'img/productos/elizabeth-arden-5th-avenue.jpg', 'floral', 'Lilas, magnolia, jazmín, rosa, almizcle, sándalo', 'Lilas, bergamota, neroli', 'Magnolia, jazmín, rosa', 'Almizcle, sándalo, ámbar', '🗽', 'Elegancia urbana, determinación, sofisticación, estilo', 'Oficina, eventos formales, uso diario, todo el año', '7-9 horas', 'Moderada', '{"principal":"#A78BFA","secundario":"#DDD6FE","acento":"#7C3AED","fondo":"#F5F3FF"}'],
        ['Beautiful', 'Estée Lauder', 'La belleza en su forma más pura. Beautiful es un jardín de rosas: la rosa, el lirio y la gardenia se entrelazan en una fragancia que es pura gracia femenina.', 'La belleza pura: rosa, lirio y gardenia en jardín de gracia femenina.', 'img/productos/estee-lauder-beautiful.jpg', 'floral', 'Rosa, lirio, gardenia, jazmín, almizcle', 'Rosa, mandarina, lichi', 'Lirio, gardenia, jazmín', 'Almizcle, sándalo, ámbar', '🌹', 'Belleza, gracia, feminidad, delicadeza', 'Eventos formales, bodas, primavera, todo el año', '7-9 horas', 'Moderada', '{"principal":"#FB7185","secundario":"#FECDD3","acento":"#E11D48","fondo":"#FFF1F2"}'],
        ['Youth Dew', 'Estée Lauder', 'Un clásico atemporal que desafía los años. Youth Dew es cálida y especiada: el clavo y la canela se mezclan con la rosa y el jazmín para crear una fragancia que es pura calidez.', 'Clásico atemporal: clavo, canela, rosa y jazmín en calidez reconfortante.', 'img/productos/estee-lauder-youth-dew.jpg', 'oriental', 'Clavo, canela, rosa, jazmín, almizcle, ámbar', 'Clavo, aldehydos, bergamota', 'Rosa, jazmín, clavel', 'Almizcle, ámbar, sándalo, vainilla', '🕰️', 'Calidez, sabiduría, atemporalidad, confort', 'Otoño/invierno, eventos formales, noches frías', '10-14 horas', 'Alta', '{"principal":"#92400E","secundario":"#D97706","acento":"#78350F","fondo":"#FFFBEB"}'],
        ['Acqua di Gio', 'Giorgio Armani', 'El mar Mediterráneo en una fragancia. Acqua di Gio es pura frescura acuática: las notas marinas y el jazmín crean una brisa salada que te transporta a la costa.', 'Mar Mediterráneo: notas marinas y jazmín en brisa salada transportadora.', 'img/productos/giorgio-armani-acqua-di-gio.jpg', 'fresco', 'Notas marinas, jazmín, limón, almizcle, cedro', 'Naranja, limón, bergamota', 'Jazmín, calona, melón', 'Cedro, almizcle, musgo', '🐚', 'Frescura, libertad, naturalidad, conexión con el mar', 'Verano, playas, uso diario, paseos', '5-7 horas', 'Suave-Moderada', '{"principal":"#38BDF8","secundario":"#E0F2FE","acento":"#0284C7","fondo":"#F0F9FF"}'],
        ['Acqua di Gioia', 'Giorgio Armani', 'La versión femenina del clásico Acqua di Gio. Gioia es alegría líquida: la menta y la lima se abren con frescura revitalizante, mientras que el jazmín y la rosa crean un corazón floral.', 'Alegría líquida: menta, lima y jazmín en frescura revitalizante.', 'img/productos/giorgio-armani-acqua-di-gioia.jpg', 'fresco', 'Menta, lima, jazmín, rosa, almizcle, cedro', 'Menta, lima, pera', 'Jazmín, peonía, rosa', 'Almizcle, cedro, azúcar', '💧', 'Alegría, diversión, frescura, vitalidad', 'Verano, uso diario, paseos, piscina', '5-7 horas', 'Moderada', '{"principal":"#06B6D4","secundario":"#A5F3FC","acento":"#0891B2","fondo":"#ECFEFF"}'],
        ['Sì', 'Giorgio Armani', 'El "sí" de la mujer que se atreve. Sì es elegancia con carácter: la grosella negra y el fresia se abren con vitalidad, mientras que la rosa y el patchouli crean un corazón profundo.', 'El sí de la valentía: grosella negra, rosa y patchouli en elegancia con carácter.', 'img/productos/giorgio-armani-si.jpg', 'elegante', 'Grosella negra, fresia, rosa, patchouli, vainilla, ambrox', 'Grosella negra, mandarina, pera', 'Fresia, rosa, peonía', 'Patchouli, vainilla, ambrox', '💋', 'Valentía, elegancia, pasión, determinación', 'Cenas elegantes, eventos formales, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#DC2626","secundario":"#FCA5A5","acento":"#B91C1C","fondo":"#FEF2F2"}'],
        ['Flora Gorgeous Magnolia', 'Gucci', 'La magnolia más hermosa del jardín de Gucci. Flora Gorgeous Magnolia es luminosa y adictiva: la magnolia y la gardenia se mezclan con notas de frutas para crear una fragancia que irradia alegría.', 'Magnolia luminosa: gardenia, frutas y almizcle en alegría radiante.', 'img/productos/gucci-flora-gorgeous-magnolia.jpg', 'floral', 'Magnolia, gardenia, frutas, almizcle, sándalo', 'Pera, limón, magnolia', 'Gardenia, jazmín, peonía', 'Almizcle, sándalo, vainilla', '🌿', 'Luminosidad, alegría, feminidad radiante', 'Primavera, verano, uso diario, paseos', '6-8 horas', 'Moderada', '{"principal":"#34D399","secundario":"#A7F3D0","acento":"#059669","fondo":"#ECFDF5"}'],
        ['The Scent For Her', 'Hugo Boss', 'La seducción hecha sistema. The Scent For Her es puro magnetismo: la freisia y el durazno se abren con dulzura, mientras que el cacao y el almizcle crean un fondo que hipnotiza.', 'Seducción sistemática: freisia, durazno y cacao en magnetismo hipnótico.', 'img/productos/hugo-boss-the-scent-her.jpg', 'oriental', 'Freisia, durazno, cacao, almizcle, sándalo', 'Freisia, durazno', 'Cacao, jazmín, osmanthus', 'Almizcle, sándalo, ámbar', '🖤', 'Seducción, magnetismo, intensidad, arte', 'Citas románticas, noches de fiesta, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#78350F","secundario":"#D97706","acento":"#451A03","fondo":"#FFFBEB"}'],
        ['L\'Eau d\'Issey', 'Issey Miyake', 'El agua más pura que jamás haya olido. L\'Eau d\'Issey es transparencia absoluta: la loto y el melón crean una frescura acuática que te limpia el alma.', 'Agua pura: loto, melón y frescura acuática que limpia el alma.', 'img/productos/issey-miyake-leau-dissey.jpg', 'fresco', 'Loto, melón, peonía, cedro, almizcle', 'Loto, melón, bergamota', 'Peonía, clavel, lirio', 'Cedro, almizcle, sándalo', '💧', 'Pureza, transparencia, revolución, naturalidad', 'Verano, uso diario, oficina, todo el año', '6-8 horas', 'Suave-Moderada', '{"principal":"#BAE6FD","secundario":"#E0F2FE","acento":"#38BDF8","fondo":"#F0F9FF"}'],
        ['Classique', 'Jean Paul Gaultier', 'La sensualidad francesa en su máxima expresión. Classique es cálida y especiada: la rosa y el jazmín se mezclan con canela y almizcle para crear una fragancia que es pura pasión francesa.', 'Sensualidad francesa: rosa, jazmín y canela en pasión nocturna parisina.', 'img/productos/jean-paul-gaultier-classique.jpg', 'oriental', 'Rosa, jazmín, canela, almizcle, ámbar, vainilla', 'Rosa, naranja, jengibre', 'Jazmín, gardenia, lirio', 'Ámbar, almizcle, vainilla, sándalo', '🗼', 'Sensualidad, pasión francesa, romance, misterio', 'Noches románticas, citas especiales, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#F59E0B","secundario":"#FDE68A","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['La Belle', 'Jean Paul Gaultier', 'La belleza en estado puro. La Belle es dulce y envolvente: la pera y la vainilla se mezclan con el haba tonka para crear una fragancia que es pura tentación.', 'Belleza pura: pera, vainilla y haba tonka en tentación envolvente.', 'img/productos/jean-paul-gaultier-la-belle.jpg', 'dulce', 'Pera, vainilla, haba tonka, almizcle, sándalo', 'Pera, bergamota', 'Vainilla, almizcle, flores blancas', 'Haba tonka, sándalo, ámbar', '👸', 'Belleza, tentación, dulzura, poder femenino', 'Citas románticas, eventos especiales, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#D4AF37","secundario":"#FDE68A","acento":"#B8860B","fondo":"#FFFBEB"}'],
        ['Viva La Juicy', 'Juicy Couture', 'La fiesta en una fragancia. Viva La Juicy es pura energía: las bayas y la mandarina crean una explosión de alegría, mientras que el jazmín y el gardenia dan elegancia.', 'La fiesta: bayas, mandarina y jazmín en explosión de alegría.', 'img/productos/juicy-couture-viva-la-juicy.jpg', 'dulce', 'Bayas, mandarina, jazmín, gardenia, vainilla, sándalo', 'Bayas, mandarina, frambuesa', 'Jazmín, gardenia, azucena', 'Vainilla, sándalo, almizcle', '🎉', 'Alegría, fiesta, diversión, energía', 'Fiestas, uso diario, verano, fins de semana', '6-8 horas', 'Moderada', '{"principal":"#F43F5E","secundario":"#FECDD3","acento":"#E11D48","fondo":"#FFF1F2"}'],
        ['Forbidden Games', 'Kilian', 'El juego prohibido que todos quieren jugar. Forbidden Games es pura tentación: la rosa y el patchouli se mezclan con la vainilla y el almizcle para crear una fragancia adictiva.', 'Tentación pura: rosa, patchouli y vainilla en juego adictivo.', 'img/productos/kilian-forbidden-games.jpg', 'oriental', 'Rosa, patchouli, vainilla, almizcle, ámbar', 'Rosa, bergamota', 'Patchouli, jazmín, orquídea', 'Vainilla, almizcle, ámbar, sándalo', '🍎', 'Tentación, misterio, adicción, peligro', 'Noches de fiesta, citas intensas, otoño/invierno', '10-12 horas', 'Muy Alta', '{"principal":"#991B1B","secundario":"#DC2626","acento":"#7F1D1D","fondo":"#FEF2F2"}'],
        ['Good Girl Gone Bad', 'Kilian', 'Cuando la buena chica se convierte en la mala. Good Girl Gone Bad es rebeldía floral: el jazmín y la rosa se mezclan con notas de tuberosa para crear una fragancia de liberación.', 'Rebeldía floral: jazmín, rosa y tuberosa en liberación salvaje.', 'img/productos/kilian-good-girl-gone-bad.jpg', 'floral', 'Jazmín, rosa, tuberosa, lirio del valle, almizcle', 'Jazmín, bergamota, petalia', 'Rosa, tuberosa, lirio', 'Almizcle, sándalo, cedro', '🔥', 'Rebeldía, liberación, pasión, libertad', 'Noches de fiesta, eventos especiales, primavera/verano', '8-10 horas', 'Alta', '{"principal":"#BE123C","secundario":"#F43F5E","acento":"#9F1239","fondo":"#FFF1F2"}'],
        ['Idôle', 'Lancôme', 'La heroína de tu propia historia. Idôle es luminosa y poderosa: la rosa y la peonía crean un corazón floral que irradia fuerza femenina.', 'Heroína propia: rosa, peonía y almizcle en luminosidad poderosa.', 'img/productos/lancome-idole.jpg', 'floral', 'Rosa, peonía, jazmín, almizcle, vainilla', 'Rosa, bergamota, pera', 'Peonía, jazmín, lirio', 'Almizcle, sándalo, vainilla', '⚡', 'Inspiración, poder femenino, luminosidad, fuerza', 'Uso diario, eventos especiales, todo el año', '8-10 horas', 'Moderada-Alta', '{"principal":"#F472B6","secundario":"#FBCFE8","acento":"#DB2777","fondo":"#FFF1F7"}'],
        ['Idôle Le Parfum', 'Lancôme', 'La intensidad de ser tú misma. Idôle Le Parfum es la versión más profunda y seductora: la rosa se intensifica con notas de ámbar y vainilla.', 'Intensidad de ser tú: rosa, ámbar y vainilla en pasión concentrada.', 'img/productos/lancome-idole-le-parfum.jpg', 'oriental', 'Rosa, ámbar, vainilla, almizcle, patchouli', 'Rosa, bergamota, naranja', 'Rosa, jazmín, iris', 'Ámbar, vainilla, almizcle', '🔥', 'Pasión, seguridad, poder, intensidad', 'Noches de fiesta, citas románticas, otoño/invierno', '10-12 horas', 'Alta', '{"principal":"#BE123C","secundario":"#FB7185","acento":"#9F1239","fondo":"#FFF1F2"}'],
        ['Idôle Nectar', 'Lancôme', 'La dulzura de ser auténtica. Idôle Nectar es adictiva: el café y la rosa se mezclan con notas de caramelo para crear una fragancia que es pura dulzura intensa.', 'Dulzura auténtica: café, rosa y caramelo en indulgencia adictiva.', 'img/productos/lancome-idole-nectar.jpg', 'dulce', 'Café, rosa, caramelo, vainilla, almizcle', 'Café, bergamota, grosella', 'Rosa, jazmín, peonía', 'Caramelo, vainilla, almizcle', '🍯', 'Indulgencia, dulzura, autenticidad, premio', 'Noches de fiesta, citas, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#D97706","secundario":"#FDE68A","acento":"#B45309","fondo":"#FFFBEB"}'],
        ['La Nuit Trésor', 'Lancôme', 'El tesoro más valioso de la noche. La Nuit Trésor es oscura y adictiva: la rosa negra y el oud se mezclan con la vainilla para crear una fragancia de tentación nocturna.', 'Tesoro nocturno: rosa negra, oud y vainilla en tentación oscura.', 'img/productos/lancome-la-nuit-tresor.jpg', 'oriental', 'Rosa negra, oud, vainilla, almizcle, lichi', 'Lichi, bergamota, pera', 'Rosa negra, orquídea, iris', 'Vainilla, oud, almizcle, patchouli', '🌙', 'Misterio, tentación, tesoro, nocturnidad', 'Noches de fiesta, citas románticas, invierno', '10-12 horas', 'Muy Alta', '{"principal":"#581C87","secundario":"#A855F7","acento":"#6B21A8","fondo":"#FAF5FF"}'],
        ['La Vie Est Belle', 'Lancôme', 'La vida es hermosa, y esta fragancia lo demuestra. La Vie Est Belle es pura felicidad: el iris y la praliné se mezclan con la vainilla para crear un aroma de explosión de alegría.', 'Felicidad pura: iris, praliné y vainilla en explosión de alegría.', 'img/productos/lancome-la-vie-est-belle.jpg', 'dulce', 'Iris, praliné, vainilla, almizcle, sándalo', 'Grosella, pera, almendra', 'Iris, jazmín, naranja en flor', 'Praliné, vainilla, sándalo, almizcle', '🌈', 'Felicidad, alegría, esperanza, positividad', 'Uso diario, eventos especiales, todo el año', '8-10 horas', 'Alta', '{"principal":"#A855F7","secundario":"#DDD6FE","acento":"#7C3AED","fondo":"#F5F3FF"}'],
        ['La Vie Est Belle L\'Eclat', 'Lancôme', 'El brillo de la felicidad en su forma más pura. L\'Eclat es luminosa y radiante: las notas de naranja y jazmín crean una explosión de luz.', 'Brillo de la felicidad: naranja, jazmín e iris en explosión de luz.', 'img/productos/lancome-la-vie-est-belle-leclat.jpg', 'floral', 'Naranja, jazmín, iris, vainilla, almizcle', 'Naranja, bergamota, limón', 'Jazmín, iris, peonía', 'Vainilla, almizcle, sándalo', '✨', 'Luminosidad, felicidad, brillo, radiación', 'Primavera, verano, uso diario, eventos', '6-8 horas', 'Moderada', '{"principal":"#FDE68A","secundario":"#FEF3C7","acento":"#F59E0B","fondo":"#FFFBEB"}'],
        ['Trésor', 'Lancôme', 'Un tesoro de elegancia atemporal. Trésor es sofisticación pura: la rosa y el lirio se entrelazan con notas de ámbar para crear una fragancia de herencia francesa.', 'Tesoro de elegancia: rosa, lirio y ámbar en sofisticación atemporal.', 'img/productos/lancome-tresor.jpg', 'elegante', 'Rosa, lirio, ámbar, almizcle, sándalo', 'Rosa, aldehydos, melocotón', 'Lirio, jazmín, ylang-ylang', 'Ámbar, almizcle, sándalo, vainilla', '💎', 'Herencia, elegancia, sofisticación, valor', 'Eventos formales, cenas elegantes, toda ocasión', '10-14 horas', 'Alta', '{"principal":"#D4AF37","secundario":"#FDE68A","acento":"#B8860B","fondo":"#FFFBEB"}'],
        ['Le Parfum', 'Lalique', 'El arte de la perfumería en estado puro. Le Parfum es compleja y fascinante: el jazmín y la rosa se entrelazan con notas de sándalo y vainilla.', 'Arte perfumado: jazmín, rosa y sándalo en sofisticación artesanal.', 'img/productos/lalique-le-parfum.jpg', 'elegante', 'Jazmín, rosa, sándalo, vainilla, almizcle', 'Bergamota, aldehído', 'Jazmín, rosa, tuberosa', 'Sándalo, vainilla, almizcle, ámbar', '🏛️', 'Arte, sofisticación, complejidad, eternidad', 'Eventos formales, cenas elegantes, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#6B7280","secundario":"#D1D5DB","acento":"#374151","fondo":"#F9FAFB"}'],
        ['Ana Abiyedh', 'Lattafa', 'La pureza blanca del Medio Oriente. Ana Abiyedh es fresca y elegante: las notas de almizcle y vainilla crean una base suave, mientras que las flores blancas dan un toque de ternura.', 'Pureza oriental: almizcle, vainilla y flores blancas en elegancia suave.', 'img/productos/lattafa-ana-abiyedh.jpg', 'fresco', 'Almizcle, vainilla, flores blancas, sándalo', 'Bergamota, aldehído', 'Flores blancas, jazmín', 'Almizcle, sándalo, vainilla', '🤍', 'Pureza, elegancia, sofisticación, suavidad', 'Uso diario, oficina, primavera/verano', '6-8 horas', 'Moderada', '{"principal":"#F5F5F4","secundario":"#E7E5E4","acento":"#A8A29E","fondo":"#FAFAF9"}'],
        ['Fakhar', 'Lattafa', 'El orgullo árabe en una fragancia. Fakhar es majestuosa y envolvente: las notas de oud y ámbar se mezclan con rosas para crear una sinfonía oriental que cautiva los sentidos.', 'Orgullo árabe: oud, ámbar y rosas en sinfonía oriental majestuosa.', 'img/productos/lattafa-fakhar.jpg', 'oriental', 'Oud, ámbar, rosa, almizcle, vainilla', 'Rosa, bergamota, azafrán', 'Oud, jazmín, patchouli', 'Ámbar, almizcle, vainilla', '👑', 'Orgullo, majestuosidad, lujo, grandeza', 'Eventos especiales, noches, otoño/invierno', '10-14 horas', 'Muy Alta', '{"principal":"#B45309","secundario":"#D97706","acento":"#92400E","fondo":"#FFFBEB"}'],
        ['Berry On Top', 'Lattafa', 'Una explosión de bayas que te roba el corazón. Berry On Top es dulce y juguetona: las moras y frambuesas se mezclan con notas florales para crear una fragancia de pura diversión.', 'Explosión de bayas: moras, frambuesas y flores en diversión pura.', 'img/productos/lattafa-berry-on-top.jpg', 'dulce', 'Mora, frambuesa, fresa, flores, vainilla', 'Mora, fresa, bergamota', 'Frambuesa, jazmín, peonía', 'Vainilla, almizcle', '🫐', 'Alegría, diversión, dulzura, juguetearía', 'Verano, uso diario, fins de semana', '5-7 horas', 'Moderada', '{"principal":"#7C3AED","secundario":"#C4B5FD","acento":"#6D28D9","fondo":"#F5F3FF"}'],
        ['Choco Overdose', 'Lattafa', 'Una sobredosis de chocolate que es pecado indulgente. Choco Overdose es pura tentación: el cacao y la vainilla se mezclan con notas de café.', 'Sobredosis de chocolate: cacao, vainilla y café en tentación adictiva.', 'img/productos/lattafa-choco-overdose.jpg', 'dulce', 'Cacao, vainilla, café, almizcle, sándalo', 'Cacao, bergamota, avellana', 'Café, jazmín, praliné', 'Vainilla, almizcle, sándalo', '🍫', 'Indulgencia, tentación, placer, dulzura', 'Otoño/invierno, noches frías, uso diario', '7-9 horas', 'Alta', '{"principal":"#78350F","secundario":"#A16207","acento":"#451A03","fondo":"#FFFBEB"}'],
        ['Cookie Crave', 'Lattafa', 'El antojo de una galleta recién horneada. Cookie Crave es dulce y reconfortante: la vainilla y el caramelo se mezclan con notas de mantequilla.', 'Antojo de galleta: vainilla, caramelo y mantequilla en nostalgia reconfortante.', 'img/productos/lattafa-cookie-crave.jpg', 'dulce', 'Vainilla, caramelo, mantequilla, almizcle, canela', 'Vainilla, bergamota', 'Caramelo, praliné, chocolate blanco', 'Almizcle, sándalo, canela', '🍪', 'Nostalgia, dulzura, reconforto, calidez', 'Otoño/invierno, uso diario, noches frías', '6-8 horas', 'Moderada', '{"principal":"#D97706","secundario":"#FDE68A","acento":"#B45309","fondo":"#FFFBEB"}'],
        ['Mallow Madness', 'Lattafa', 'La locura de los malvaviscos en forma de fragancia. Mallow Madness es pura diversión: los malvaviscos y la vainilla crean una mezcla adictiva y juguetona.', 'Locura de malvaviscos: malvavisco y vainilla en diversión adictiva.', 'img/productos/lattafa-mallow-madness.jpg', 'dulce', 'Malvavisco, vainilla, almizcle, azúcar', 'Malvavisco, fresa', 'Vainilla, praliné', 'Almizcle, sándalo', '🍬', 'Diversión, dulzura, juguetearía, alegría', 'Verano, uso diario, fins de semana', '5-7 horas', 'Suave-Moderada', '{"principal":"#F9A8D4","secundario":"#FBCFE8","acento":"#EC4899","fondo":"#FFF1F7"}'],
        ['Vanilla Freak', 'Lattafa', 'La vanilista más intensa que conoces. Vanilla Freak es pura vanilla en estado puro: notas de vainilla de Madagascar y Bourbon crean una fragancia adictiva y reconfortante.', 'Vanilla pura: vainilla de Madagascar y Bourbon en intensidad adictiva.', 'img/productos/lattafa-vanilla-freak.jpg', 'dulce', 'Vainilla, almizcle, sándalo, ámbar', 'Vainilla, bergamota, almendra', 'Vainilla, jazmín', 'Sándalo, almizcle, ámbar', '🍦', 'Pasión, dulzura, reconforto, adicción', 'Otoño/invierno, uso diario, noches frías', '8-10 horas', 'Alta', '{"principal":"#FDE68A","secundario":"#FEF3C7","acento":"#F59E0B","fondo":"#FFFBEB"}'],
        ['Yara', 'Lattafa', 'La princesa árabe moderna. Yara es dulce y envolvente: la fresa y el coco se mezclan con notas de vainilla y almizcle para crear una fragancia de elegancia juvenil.', 'Princesa moderna: fresa, coco y vainilla en elegancia juvenil.', 'img/productos/lattafa-yara.jpg', 'dulce', 'Fresa, coco, vainilla, almizcle, orquídea', 'Fresa, bergamota, lichi', 'Coco, orquídea, jazmín', 'Vainilla, almizcle, sándalo', '🌸', 'Elegancia juvenil, dulzura, modernidad, tradición', 'Uso diario, citas, verano, primavera', '7-9 horas', 'Moderada', '{"principal":"#F472B6","secundario":"#FBCFE8","acento":"#DB2777","fondo":"#FFF1F7"}'],
        ['Yara Elixir', 'Lattafa', 'La versión intensa y seductora de Yara. Yara Elixir es más profunda y misteriosa: las notas de frutas se intensifican con ámbar y oud.', 'Yara intensa: frutas, ámbar y oud en tentación oriental profunda.', 'img/productos/lattafa-yara-elixir.jpg', 'oriental', 'Frutas, ámbar, oud, vainilla, almizcle', 'Frutas, bergamota', 'Oud, jazmín, rosa', 'Ámbar, vainilla, almizcle', '🔥', 'Seducción, misterio, intensidad, poder', 'Noches de fiesta, citas románticas, otoño/invierno', '10-12 horas', 'Muy Alta', '{"principal":"#B91C1C","secundario":"#F87171","acento":"#991B1B","fondo":"#FEF2F2"}'],
        ['Yara Pink', 'Lattafa', 'La versión rosada y romántica de Yara. Yara Pink es más suave y femenina: la fresa y la peonía crean una fragancia de pura ternura.', 'Yara rosada: fresa y peonía en ternura femenina.', 'img/productos/lattafa-yara-pink.jpg', 'floral', 'Fresa, peonía, vainilla, almizcle', 'Fresa, bergamota', 'Peonía, jazmín', 'Vainilla, almizcle', '🩷', 'Ternura, romanticismo, dulzura, feminidad', 'Primavera, verano, uso diario, citas', '6-8 horas', 'Moderada', '{"principal":"#FB7185","secundario":"#FECDD3","acento":"#E11D48","fondo":"#FFF1F2"}'],
        ['Yara Tendance', 'Lattafa', 'La tendencia más fresca de la familia Yara. Yara Tendance es más ligera y cítrica: la bergamota y el jazmín crean una fragancia de frescura moderna.', 'Tendencia fresca: bergamota, jazmín y almizcle en modernidad ligera.', 'img/productos/lattafa-yara-tendance.jpg', 'fresco', 'Bergamota, jazmín, almizcle, sándalo', 'Bergamota, limón', 'Jazmín, peonía', 'Almizcle, sándalo', '潮流', 'Frescura, modernidad, estilo, tendencia', 'Verano, uso diario, playas, paseos', '5-7 horas', 'Suave-Moderada', '{"principal":"#06B6D4","secundario":"#A5F3FC","acento":"#0891B2","fondo":"#ECFEFF"}'],
        ['Baccarat Rouge 540', 'Maison Francis Kurkdjian', 'La joya más preciada de la perfumería moderna. Baccarat Rouge 540 es pura alquimia: el azafrán y el jazmín se funden con el ámbar gris y el cedro.', 'Alquimia pura: azafrán, jazmín y ámbar gris en joya de lujo eterno.', 'img/productos/maison-francis-kurkdjian-baccarat-rouge-540.jpg', 'oriental', 'Azafrán, jazmín, ámbar gris, cedro, almizcle', 'Azafrán, bergamota', 'Jazmín, almizcle', 'Ámbar gris, cedro, resina', '💎', 'Lujo, exclusividad, alquimia, eternidad', 'Eventos de alto nivel, cenas exclusivas, toda ocasión', '12-16 horas', 'Muy Alta', '{"principal":"#D4AF37","secundario":"#FDE68A","acento":"#B8860B","fondo":"#FFFBEB"}'],
        ['Beautiful', 'Michael Kors', 'La belleza americana en su máxima expresión. Beautiful es luminosa y poderosa: la gardenia y la peonía crean un corazón floral que irradia confianza.', 'Belleza americana: gardenia, peonía y almizcle en luminosidad poderosa.', 'img/productos/michael-kors-beautiful.jpg', 'floral', 'Gardenia, peonía, jazmín, almizcle, sándalo', 'Bergamota, pera, gardenia', 'Peonía, jazmín, lirio', 'Almizcle, sándalo, ámbar', '🗽', 'Confianza, elegancia, poder femenino', 'Oficina, eventos, uso diario, todo el año', '7-9 horas', 'Moderada', '{"principal":"#F472B6","secundario":"#FBCFE8","acento":"#DB2777","fondo":"#FFF1F7"}'],
        ['Roses Musk', 'Montale', 'La rosa más intensa del desierto. Roses Musk es pura pasión árabe: la rosa y el almizcle se entrelazan en una fragancia majestuosa y envolvente.', 'Rosa del desierto: rosa y almizcle en pasión majestuosa.', 'img/productos/montale-roses-musk.jpg', 'oriental', 'Rosa, almizcle, ámbar, oud', 'Rosa, bergamota', 'Rosa, jazmín', 'Almizcle, ámbar, oud', '🌹', 'Poder, feminidad, majestuosidad, pasión', 'Eventos especiales, noches, otoño/invierno', '10-14 horas', 'Muy Alta', '{"principal":"#E11D48","secundario":"#FECDD3","acento":"#BE123C","fondo":"#FFF1F2"}'],
        ['Signature', 'Montblanc', 'La firma de elegancia accesible. Signature es fresca y elegante: la magnolia y el almizcle crean una fragancia de sofisticación sin pretensiones.', 'Firma de elegancia: magnolia y almizcle en sofisticación accesible.', 'img/productos/montblanc-signature.jpg', 'fresco', 'Magnolia, almizcle, cedro, bergamota', 'Bergamota, clementina', 'Magnolia, jazmín', 'Almizcle, cedro, ámbar', '✍️', 'Elegancia, sofisticación, simplicidad, poder', 'Oficina, uso diario, todo el año', '6-8 horas', 'Moderada', '{"principal":"#6B7280","secundario":"#D1D5DB","acento":"#374151","fondo":"#F9FAFB"}'],
        ['Alien', 'Mugler', 'La extraterrestre más seductora del universo. Alien es misteriosa y luminosa: el jazmín sambac y el ámbar gris crean una fragancia completamente fuera de este mundo.', 'Misterio alienígena: jazmín sambac y ámbar gris en luminosidad extraterrestre.', 'img/productos/mugler-alien.jpg', 'oriental', 'Jazmín sambac, ámbar gris, madera de casia', 'Jazmín sambac, bergamota', 'Jazmín, almizcle', 'Ámbar gris, madera de casia', '👽', 'Misterio, luminosidad, enigma, poder', 'Noches de fiesta, eventos especiales, otoño/invierno', '10-14 horas', 'Muy Alta', '{"principal":"#7C3AED","secundario":"#C4B5FD","acento":"#5B21B6","fondo":"#F5F3FF"}'],
        ['For Her', 'Narciso Rodriguez', 'La esencia de la femineidad moderna. For Her es almizcle puro: la rosa y el peonía se entrelazan con almizcle en una fragancia sensual pero elegante.', 'Femineidad moderna: rosa, peonía y almizcle en sensualidad sutil.', 'img/productos/narciso-rodriguez-for-her.jpg', 'floral', 'Rosa, peonía, almizcle, ámbar, sándalo', 'Rosa, bergamota', 'Peonía, almizcle, jazmín', 'Ámbar, sándalo, almizcle', '🖤', 'Sensualidad, elegancia, sutileza, femineidad', 'Citas románticas, uso diario, todo el año', '8-10 horas', 'Moderada', '{"principal":"#1F2937","secundario":"#6B7280","acento":"#111827","fondo":"#F9FAFB"}'],
        ['L\'Extase', 'Nina Ricci', 'El éxtasis de la feminidad en estado puro. L\'Extase es dulce y envolvente: la rosa y el almizcle crean una fragancia de tentación suave.', 'Éxtasis femenino: rosa y almizcle en tentación suave y libertad.', 'img/productos/nina-ricci-lextase.jpg', 'floral', 'Rosa, almizcle, iris, vainilla', 'Rosa, bergamota', 'Rosa, iris, peonía', 'Almizcle, vainilla, sándalo', '🦋', 'Libertad, éxtasis, dulzura, feminidad', 'Citas románticas, primavera/verano, uso diario', '6-8 horas', 'Moderada', '{"principal":"#F9A8D4","secundario":"#FDE68A","acento":"#EC4899","fondo":"#FFF7ED"}'],
        ['Dania', 'Orientica', 'La elegancia oriental accesible. Dania es suave y envolvente: las notas de flores y almizcle crean una fragancia de pura gracia.', 'Elegancia oriental: flores y almizcle en gracia serena.', 'img/productos/orientica-dania.jpg', 'floral', 'Flores, almizcle, sándalo, vainilla', 'Bergamota, pera', 'Flores blancas, jazmín', 'Almizcle, sándalo, vainilla', '🪷', 'Serenidad, gracia, elegancia, simplicidad', 'Uso diario, oficina, primavera/verano', '6-8 horas', 'Moderada', '{"principal":"#A78BFA","secundario":"#DDD6FE","acento":"#7C3AED","fondo":"#F5F3FF"}'],
        ['Heiress', 'Paris Hilton', 'La heredera de la fortuna más fresca. Heiress es tropical y divertida: la passion fruit y la gardenia crean una fragancia de pura diversión de verano.', 'Heredera tropical: passion fruit y gardenia en diversión lujosa.', 'img/productos/paris-hilton-heiress.jpg', 'floral', 'Passion fruit, gardenia, almizcle, sándalo', 'Passion fruit, bergamota', 'Gardenia, jazmín, champaca', 'Almizcle, sándalo, ámbar', '🏝️', 'Diversión, lujos, frescura tropical', 'Verano, playas, fiestas, fins de semana', '5-7 horas', 'Moderada', '{"principal":"#F59E0B","secundario":"#FDE68A","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['Rush', 'Paris Hilton', 'La carrera más divertida de tu vida. Rush es energética y vibrante: las notas de frutas y flores crean una fragancia de pura adrenalina.', 'Adrenalina pura: frutas y flores en carrera vibrante.', 'img/productos/paris-hilton-rush.jpg', 'floral', 'Frutas, flores, almizcle, ámbar', 'Mandarina, pera, frambuesa', 'Jazmín, gardenia, lirio', 'Ámbar, almizcle, sándalo', '🎢', 'Emoción, adrenalina, diversión, energía', 'Fiestas, verano, uso diario, fins de semana', '5-7 horas', 'Moderada', '{"principal":"#F43F5E","secundario":"#FECDD3","acento":"#E11D48","fondo":"#FFF1F2"}'],
        ['Delina Exclusif', 'Parfums de Marly', 'La exclusividad hecha fragancia. Delina Exclusif es pura elegancia oriental: la rosa turca y el lichi se mezclan con ámbar y vainilla.', 'Exclusividad: rosa turca, lichi y ámbar en elegancia lujosa.', 'img/productos/parfums-de-marly-delina-exclusif.jpg', 'oriental', 'Rosa turca, lichi, ámbar, vainilla, almizcle', 'Lichi, bergamota, peonía', 'Rosa turca, patchouli', 'Ámbar, vainilla, almizcle', '👑', 'Exclusividad, lujo, elegancia, merecimiento', 'Eventos de alto nivel, cenas exclusivas', '10-14 horas', 'Muy Alta', '{"principal":"#BE123C","secundario":"#FB7185","acento":"#9F1239","fondo":"#FFF1F2"}'],
        ['Candy', 'Prada', 'El dulce más sofisticado del mundo. Candy es adictiva y elegante: la vainilla y el ámbar se mezclan con notas de peonia para crear una fragancia dulce pero nunca empalagosa.', 'Dulce sofisticado: vainilla, ámbar y peonia en indulgencia elegante.', 'img/productos/prada-candy.jpg', 'dulce', 'Vainilla, ámbar, peonia, almizcle', 'Vainilla, bergamota', 'Peonia, almizcle', 'Ámbar, almizcle, sándalo', '🍬', 'Indulgencia, dulzura, sofisticación, placer', 'Citas, noches, otoño/invierno', '8-10 horas', 'Alta', '{"principal":"#F59E0B","secundario":"#FDE68A","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['La Femme', 'Prada', 'La mujer en su forma más pura y elegante. La Femme es floral y sofisticada: la miel y la gardenia se entrelazan con notas de ámbar.', 'Gracia pura: miel, gardenia y ámbar en elegancia sin esfuerzo.', 'img/productos/prada-la-femme.jpg', 'floral', 'Miel, gardenia, ámbar, almizcle, cedro', 'Bergamota, aframones', 'Gardenia, jazmín, ylang-ylang', 'Ámbar, almizcle, cedro', '🐝', 'Elegancia, gracia, sofisticación, simplicidad', 'Oficina, eventos formales, todo el año', '8-10 horas', 'Moderada-Alta', '{"principal":"#D4AF37","secundario":"#FDE68A","acento":"#B8860B","fondo":"#FFFBEB"}'],
        ['Ralph', 'Ralph Lauren', 'El espíritu americano en su forma más fresca. Ralph es juvenil y vibrante: las notas de manzana y freesia crean una fragancia de pura energía americana.', 'Espíritu americano: manzana, freesia y frescura juvenil vibrante.', 'img/productos/ralph-lauren-ralph.jpg', 'fresco', 'Manzana, freesia, almizcle, cedro', 'Manzana, mandarina, loto', 'Freesia, rosa, jazmín', 'Almizcle, cedro, musgo', '🍎', 'Juventud, energía, frescura, ambición', 'Primavera, verano, uso diario, universidad', '5-7 horas', 'Moderada', '{"principal":"#DC2626","secundario":"#FCA5A5","acento":"#B91C1C","fondo":"#FEF2F2"}'],
        ['Bitter Peach', 'Tom Ford', 'El durazno más seductor del mundo. Bitter Peach es dulce y profundo: el durazno y el ámbar se mezclan con notas de patchouli.', 'Durazno seductor: durazno, ámbar y patchouli en tentación concentrada.', 'img/productos/tom-ford-bitter-peach.jpg', 'oriental', 'Durazno, ámbar, patchouli, vainilla, almizcle', 'Durazno, bergamota', 'Patchouli, jazmín, cardamomo', 'Ámbar, vainilla, almizcle', '🍑', 'Tentación, sensualidad, dulzura profunda', 'Noches de fiesta, citas románticas, verano', '8-10 horas', 'Alta', '{"principal":"#F97316","secundario":"#FDBA74","acento":"#EA580C","fondo":"#FFF7ED"}'],
        ['Lost Cherry', 'Tom Ford', 'La cereza perdida que todos buscan. Lost Cherry es adictiva y misteriosa: la cereza y el almizcle crean una fragancia de pura tentación oscura.', 'Cereza misteriosa: cereza, almizcle y ámbar en tentación oscura.', 'img/productos/tom-ford-lost-cherry.jpg', 'oriental', 'Cereza, almizcle, ámbar, tonka, café', 'Cereza, bergamota', 'Almizcle, jazmín, rosa', 'Ámbar, tonka, café', '🍒', 'Misterio, tentación, adicción, oscuridad', 'Noches de fiesta, citas intensas, otoño/invierno', '10-12 horas', 'Muy Alta', '{"principal":"#991B1B","secundario":"#DC2626","acento":"#7F1D1D","fondo":"#FEF2F2"}'],
        ['Noir de Noir', 'Tom Ford', 'El negro más elegante del mundo. Noir de Noir es oscura y lujosa: la rosa negra y el oud se entrelazan con notas de trufa.', 'Negro elegante: rosa negra, oud y trufa en exclusividad oscura.', 'img/productos/tom-ford-noir-de-noir.jpg', 'oriental', 'Rosa negra, oud, trufa, ámbar, vainilla', 'Rosa negra, azafrán', 'Oud, patchouli, violetas', 'Ámbar, vainilla, almizcle', '🖤', 'Exclusividad, misterio, lujo, oscuridad', 'Eventos exclusivos, noches, invierno', '12-16 horas', 'Muy Alta', '{"principal":"#111827","secundario":"#374151","acento":"#1F2937","fondo":"#F9FAFB"}'],
        ['Oud Wood', 'Tom Ford', 'La madera más preciada del Medio Oriente. Oud Wood es majestuosa y envolvente: el oud y la madera de sándalo se mezclan con vainilla.', 'Madera preciada: oud, sándalo y vainilla en calidez oriental majestuosa.', 'img/productos/tom-ford-oud-wood.jpg', 'oriental', 'Oud, sándalo, vainilla, ámbar, almizcle', 'Oud, bergamota', 'Sándalo, jazmín', 'Vainilla, ámbar, almizcle', '🪵', 'Calidez, majestuosidad, lujo, eternidad', 'Eventos formales, noches frías, invierno', '10-14 horas', 'Muy Alta', '{"principal":"#78350F","secundario":"#A16207","acento":"#451A03","fondo":"#FFFBEB"}'],
        ['Soleil Blanc', 'Tom Ford', 'El sol blanco más brillante del Caribe. Soleil Blanc es luminosa y solar: la cardamomo y la ylang-ylang crean una fragancia de pura luz tropical.', 'Sol caribeño: cardamomo, ylang-ylang y almizcle en luz solar.', 'img/productos/tom-ford-soleil-blanc.jpg', 'fresco', 'Cardamomo, ylang-ylang, almizcle, ámbar', 'Cardamomo, bergamota, coco', 'Ylang-ylang, jazmín, naranja en flor', 'Almizcle, ámbar, sándalo', '☀️', 'Luz, alegría, frescura solar, relajación', 'Verano, playas, trópicos, vacaciones', '6-8 horas', 'Moderada', '{"principal":"#FDE68A","secundario":"#FEF3C7","acento":"#F59E0B","fondo":"#FFFBEB"}'],
        ['Tobacco Vanille', 'Tom Ford', 'El tabaco más dulce y seductor del mundo. Tobacco Vanille es cálida y adictiva: el tabaco y la vainilla se mezclan con notas de cacao y canela.', 'Tabaco dulce: tabaco, vainilla y cacao en indulgencia cálida.', 'img/productos/tom-ford-tobacco-vanille.jpg', 'oriental', 'Tabaco, vainilla, cacao, canela, almizcle', 'Tabaco, bergamota', 'Cacao, jazmín, tonka', 'Vainilla, almizcle, sándalo', '🍂', 'Calidez, indulgencia, confort, adicción', 'Otoño/invierno, noches frías, uso nocturno', '10-14 horas', 'Muy Alta', '{"principal":"#92400E","secundario":"#B45309","acento":"#78350F","fondo":"#FFFBEB"}'],
        ['Donna Born in Roma', 'Valentino', 'Nacida en Roma, hecha para el mundo. Donna Born in Roma es elegancia italiana moderna: la grosella negra y el jazmín se mezclan con vainilla.', 'Elegancia romana: grosella negra, jazmín y vainilla en sofisticación con actitud.', 'img/productos/valentino-donna-born-in-roma.jpg', 'elegante', 'Grosella negra, jazmín, vainilla, almizcle', 'Grosella negra, bergamota', 'Jazmín, gardenia', 'Vainilla, almizcle, patchouli', '🏛️', 'Elegancia, actitud, sofisticación, poder', 'Eventos formales, noches, todo el año', '8-10 horas', 'Alta', '{"principal":"#BE123C","secundario":"#FB7185","acento":"#9F1239","fondo":"#FFF1F2"}'],
        ['Bombshell', 'Victoria\'s Secret', 'La bomba más sexy de Victoria\'s Secret. Bombshell es vibrante y seductora: la pasión de maracuyá y la violeta se mezclan con almizcle.', 'Bomba seductora: maracuyá, violeta y almizcle en confianza pura.', 'img/productos/victorias-secret-bombshell.jpg', 'floral', 'Maracuyá, violeta, almizcle, gardenia, sándalo', 'Maracuyá, bergamota, naranja', 'Violeta, gardenia, jazmín', 'Almizcle, sándalo, ámbar', '💣', 'Seducción, confianza, vitalidad, glamour', 'Fiestas, citas, verano, uso diario', '6-8 horas', 'Moderada', '{"principal":"#EC4899","secundario":"#F9A8D4","acento":"#DB2777","fondo":"#FFF1F7"}'],
        ['Tease Rebel', 'Victoria\'s Secret', 'La rebelde más sexy de Victoria\'s Secret. Tease Rebel es atrevida y adictiva: la manzana y la gardenia se mezclan con notas de cuero.', 'Rebelde atrevida: manzana, gardenia y cuero en rebeldía femenina.', 'img/productos/victorias-secret-tease-rebel.jpg', 'oriental', 'Manzana, gardenia, cuero, almizcle, ámbar', 'Manzana, bergamota', 'Gardenia, jazmín, rosa', 'Cuero, almizcle, ámbar', '🏍️', 'Rebeldía, libertad, atrevimiento, pasión', 'Fiestas, noches, uso diario, todo el año', '7-9 horas', 'Moderada-Alta', '{"principal":"#1F2937","secundario":"#6B7280","acento":"#374151","fondo":"#F9FAFB"}'],
        ['Bright Crystal', 'Versace', 'El cristal más brillante del palacio de Versace. Bright Crystal es luminosa y fresca: el granado y la peonia crean una fragancia de pura luz cristalina.', 'Cristal luminoso: granado, peonia y almizcle en luz brillante.', 'img/productos/versace-bright-crystal.jpg', 'fresco', 'Granado, peonia, almizcle, cedro, magnolia', 'Granado, bergamota, lichi', 'Peonia, magnolia, loto', 'Almizcle, cedro, musgo', '💎', 'Luminosidad, frescura, elegancia, brillantez', 'Primavera, verano, uso diario, eventos', '6-8 horas', 'Moderada', '{"principal":"#F472B6","secundario":"#FBCFE8","acento":"#DB2777","fondo":"#FFF1F7"}'],
        ['Eros Pour Femme', 'Versace', 'La versión femenina del amor más poderoso del mundo. Eros Pour Femme es sensual y luminosa: el limón y la granada se mezclan con jazmín y almizcle.', 'Pasión luminosa: limón, granada y jazmín en sensualidad divina.', 'img/productos/versace-eros-pour-femme.jpg', 'floral', 'Limón, granada, jazmín, almizcle, sándalo', 'Limón, bergamota, granada', 'Jazmín, peonia, lirio', 'Almizcle, sándalo, ámbar', '💘', 'Pasión, poder, sensualidad, inmortalidad', 'Citas románticas, noches, verano', '8-10 horas', 'Alta', '{"principal":"#10B981","secundario":"#A7F3D0","acento":"#059669","fondo":"#ECFDF5"}'],
        ['Versense', 'Versace', 'La frescura de Versace en su forma más pura. Versense es cítrica y floral: el bergamota y la mandarina se mezclan con jazmín.', 'Frescura vital: bergamota, mandarina y jazmín en vitalidad pura.', 'img/productos/versace-versense.jpg', 'fresco', 'Bergamota, mandarina, jazmín, almizcle, cedro', 'Bergamota, mandarina, pera', 'Jazmín, gardenia, pruno', 'Almizcle, cedro, olivo', '🌊', 'Frescura, vitalidad, relajación, Mediterráneo', 'Verano, uso diario, playas, paseos', '5-7 horas', 'Suave-Moderada', '{"principal":"#34D399","secundario":"#A7F3D0","acento":"#059669","fondo":"#ECFDF5"}'],
        ['Black Opium', 'YSL', 'La adicción más elegante del mundo. Black Opium es oscura y adictiva: el café y la vainilla se mezclan con notas de flores.', 'Adicción elegante: café, vainilla y flores en tentación nocturna.', 'img/productos/ysl-black-opium.jpg', 'oriental', 'Café, vainilla, flores, almizcle, ámbar', 'Café, pera, bergamota', 'Flores, jazmín, naranja en flor', 'Vainilla, almizcle, patchouli', '☕', 'Adicción, misterio, tentación, elegancia', 'Noches de fiesta, citas, otoño/invierno', '8-12 horas', 'Alta', '{"principal":"#111827","secundario":"#6B7280","acento":"#374151","fondo":"#F9FAFB"}'],
        ['Libre', 'YSL', 'La libertad hecha fragancia. Libre es poderosa y luminosa: la lavanda y la naranja se mezclan con flores para crear una fragancia de pura liberación.', 'Libertad pura: lavanda, naranja y flores en liberación luminosa.', 'img/productos/ysl-libre.jpg', 'elegante', 'Lavanda, naranja, flores, almizcle, ámbar', 'Lavanda, bergamota, naranja', 'Flores, jazmín, gardenia', 'Ámbar, almizcle, musgo', '🕊️', 'Libertad, valentía, poder, luminosidad', 'Uso diario, eventos, todo el año', '8-10 horas', 'Alta', '{"principal":"#F59E0B","secundario":"#FDE68A","acento":"#D97706","fondo":"#FFFBEB"}'],
        ['Mon Paris', 'YSL', 'El amor más intenso de París. Mon Paris es romántica y adictiva: la fresa y el jazmín se mezclan con patchouli para crear una fragancia de pasión parisina.', 'Amor parisino: fresa, jazmín y patchouli en pasión intensa.', 'img/productos/ysl-mon-paris.jpg', 'floral', 'Fresa, jazmín, patchouli, almizcle, ámbar', 'Fresa, bergamota, pera', 'Jazmín, peonía, gardenia', 'Patchouli, almizcle, ámbar', '🗼', 'Romanticismo, pasión, intensidad, amor', 'Citas románticas, noches, todo el año', '8-10 horas', 'Alta', '{"principal":"#FB7185","secundario":"#FECDD3","acento":"#E11D48","fondo":"#FFF1F2"}'],
        ['This is Her', 'Zadig & Voltaire', 'La mujer auténtica sin filtros. This is Her es suave y envolvente: la castaña y la vainilla se mezclan con notas de jazmín.', 'Autenticidad pura: castaña, vainilla y jazmín en comodidad envolvente.', 'img/productos/zadig-voltaire-this-is-her.jpg', 'dulce', 'Castaña, vainilla, jazmín, almizcle, sándalo', 'Castaña, bergamota', 'Jazmín, gardenia', 'Vainilla, almizcle, sándalo', '🖤', 'Autenticidad, comodidad, seguridad, suavidad', 'Uso diario, otoño/invierno, noches frías', '6-8 horas', 'Moderada', '{"principal":"#6B7280","secundario":"#D1D5DB","acento":"#374151","fondo":"#F9FAFB"}']
    ];

    // Preparar statement de inserción
    $sql = "INSERT INTO productos (nombre, marca, descripcion, descripcion_corta, imagen, categoria, tipo_olor, notas, notas_salida, notas_corazon, notas_fondo, emoji, transmite, ideal_para, duracion, intensidad, colores, precio, activo, destacado) VALUES (?, ?, ?, ?, ?, 'mujer', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, 1, 0)";
    $stmt = $pdo->prepare($sql);

    $insertados = 0;
    $errores = 0;
    $total = count($productos);

    foreach ($productos as $i => $p) {
        $pct = 10 + round(($i / $total) * 85);
        updateProgress($pct);
        
        try {
            $stmt->execute($p);
            $insertados++;
            if (($insertados % 10) == 0) {
                addStatus("Insertados $insertados de $total productos...", "ok");
            }
        } catch (PDOException $e) {
            $errores++;
            addStatus("Error insertando '{$p[0]}': " . $e->getMessage(), "error");
        }
    }

    updateProgress(95);
    addStatus("Importación completada: $insertados productos insertados, $errores errores.", $errores > 0 ? "warning" : "ok");
}

// Verificar total final
$finalCount = $pdo->query("SELECT COUNT(*) as total FROM productos WHERE categoria = 'mujer' AND activo = 1")->fetch()['total'];
$totalAll = $pdo->query("SELECT COUNT(*) as total FROM productos WHERE activo = 1")->fetch()['total'];

updateProgress(100);

echo "<div class='count'>$finalCount</div>";
echo "<div class='count-label'>perfumes de mujer en la base de datos</div>";
echo "<div class='count' style='font-size: 24px;'>$totalAll</div>";
echo "<div class='count-label'>productos totales (hombre + mujer)</div>";

addStatus("¡CATÁLOGO IMPORTADO EXITOSAMENTE!", "ok");
addStatus("Ya puedes visitar <a href='https://manizales-pf.great-site.net' target='_blank'>manizales-pf.great-site.net</a> y ver los perfumes.", "ok");
addStatus("<strong>IMPORTANTE:</strong> Elimina este archivo (importar_catalogo.php) del servidor por seguridad.", "warning");

echo "<div class='footer-note'>";
echo "<p>Manizales Perfumería - Importador de Catálogo</p>";
echo "<p>Este script se puede eliminar después de usarlo.</p>";
echo "</div>";
echo "</div></body></html>";
?>
